# COMANDOS PARA EXECUÇÃO PARALELA - AMBOS OS EXPERIMENTOS
# Total of seeds: 30
# Total of commands: 120
# Commands per seed: 4 (2 mkdir + 2 python)
# Simples tests per seed: 180
# Power-Law tests per seed: 90
# Simples graphs per seed: 9000
# Power-Law graphs per seed: 4500
# Thread limit: 24 threads per process

mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2700001
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2700001
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2700001 --seeds 2700001 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2700001/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2700001 --seeds 2700001 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2700001/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3170702080
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3170702080
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3170702080 --seeds 3170702080 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3170702080/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3170702080 --seeds 3170702080 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3170702080/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3548644859
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3548644859
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3548644859 --seeds 3548644859 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3548644859/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3548644859 --seeds 3548644859 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3548644859/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1033592630
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1033592630
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1033592630 --seeds 1033592630 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1033592630/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1033592630 --seeds 1033592630 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1033592630/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/9263589860
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/9263589860
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/9263589860 --seeds 9263589860 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/9263589860/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/9263589860 --seeds 9263589860 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/9263589860/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1883634842
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1883634842
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1883634842 --seeds 1883634842 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1883634842/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1883634842 --seeds 1883634842 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1883634842/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/7648101510
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/7648101510
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/7648101510 --seeds 7648101510 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/7648101510/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/7648101510 --seeds 7648101510 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/7648101510/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1502014705
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1502014705
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1502014705 --seeds 1502014705 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1502014705/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1502014705 --seeds 1502014705 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1502014705/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/7214842310
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/7214842310
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/7214842310 --seeds 7214842310 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/7214842310/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/7214842310 --seeds 7214842310 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/7214842310/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2606453957
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2606453957
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2606453957 --seeds 2606453957 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2606453957/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2606453957 --seeds 2606453957 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2606453957/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/4194499680
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/4194499680
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/4194499680 --seeds 4194499680 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/4194499680/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/4194499680 --seeds 4194499680 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/4194499680/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2779365847
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2779365847
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2779365847 --seeds 2779365847 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2779365847/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2779365847 --seeds 2779365847 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2779365847/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1094121244
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1094121244
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1094121244 --seeds 1094121244 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1094121244/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1094121244 --seeds 1094121244 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1094121244/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1090525961
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1090525961
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1090525961 --seeds 1090525961 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1090525961/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1090525961 --seeds 1090525961 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1090525961/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3310223418
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3310223418
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3310223418 --seeds 3310223418 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3310223418/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3310223418 --seeds 3310223418 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3310223418/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/604827988
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/604827988
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/604827988 --seeds 604827988 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/604827988/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/604827988 --seeds 604827988 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/604827988/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1549035388
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1549035388
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1549035388 --seeds 1549035388 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1549035388/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1549035388 --seeds 1549035388 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1549035388/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/795578792
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/795578792
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/795578792 --seeds 795578792 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/795578792/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/795578792 --seeds 795578792 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/795578792/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/182649370
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/182649370
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/182649370 --seeds 182649370 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/182649370/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/182649370 --seeds 182649370 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/182649370/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1127200130
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1127200130
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1127200130 --seeds 1127200130 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1127200130/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1127200130 --seeds 1127200130 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1127200130/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/332728275
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/332728275
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/332728275 --seeds 332728275 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/332728275/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/332728275 --seeds 332728275 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/332728275/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1477598055
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1477598055
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1477598055 --seeds 1477598055 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1477598055/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1477598055 --seeds 1477598055 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1477598055/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1157679575
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1157679575
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1157679575 --seeds 1157679575 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1157679575/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1157679575 --seeds 1157679575 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1157679575/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3489403805
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3489403805
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3489403805 --seeds 3489403805 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3489403805/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3489403805 --seeds 3489403805 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3489403805/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/359655529
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/359655529
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/359655529 --seeds 359655529 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/359655529/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/359655529 --seeds 359655529 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/359655529/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3107219804
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3107219804
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3107219804 --seeds 3107219804 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3107219804/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3107219804 --seeds 3107219804 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3107219804/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/911079554
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/911079554
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/911079554 --seeds 911079554 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/911079554/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/911079554 --seeds 911079554 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/911079554/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1642444692
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1642444692
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1642444692 --seeds 1642444692 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/1642444692/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1642444692 --seeds 1642444692 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/1642444692/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3959116112
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3959116112
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3959116112 --seeds 3959116112 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/3959116112/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3959116112 --seeds 3959116112 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/3959116112/log.txt
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2991474091
mkdir -p /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2991474091
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/simples.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2991474091 --seeds 2991474091 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_simples_completo/2991474091/log.txt
export OMP_NUM_THREADS=24 && export MKL_NUM_THREADS=24 && python /home/cea/projects/gerador_grafos/src/experimentos/power_law.py --output_dir /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2991474091 --seeds 2991474091 &> /home/cea/projects/gerador_grafos/resultados_experimentos/exp_powerlaw_completo/2991474091/log.txt
