mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/2700001
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/2700001
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/3170702080
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/3170702080
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/3548644859
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/3548644859
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1033592630
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1033592630
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/9263589860
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/9263589860
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1883634842
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1883634842
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/7648101510
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/7648101510
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1502014705
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1502014705
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/7214842310
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/7214842310
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/2606453957
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/2606453957
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/4194499680
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/4194499680
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/2779365847
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/2779365847
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1094121244
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1094121244
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1090525961
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1090525961
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/3310223418
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/3310223418
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/604827988
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/604827988
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1549035388
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1549035388
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/795578792
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/795578792
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/182649370
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/182649370
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1127200130
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1127200130
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/332728275
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/332728275
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1477598055
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1477598055
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1157679575
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1157679575
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/3489403805
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/3489403805
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/359655529
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/359655529
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/3107219804
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/3107219804
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/911079554
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/911079554
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/1642444692
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/1642444692
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/3959116112
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/3959116112
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_simples_completo/2991474091
mkdir -p C:\Users\gusta\OneDrive\GUSTAVO\Unifei\TCC\Gerador\resultados_experimentos/exp_powerlaw_completo/2991474091
